css-brochure-form | Rocky Truong
rocky-truong/c0321-code-solutions pull request #17
Opened 2021-03-12 17:55 UTC by rocky-truong

![image](https://user-images.githubusercontent.com/58172952/110979092-036f9f00-8319-11eb-949d-87e70188063d.png)

I'm having trouble moving the last few things around.
This is what I have so far.

2021-03-12 19:23 UTC, codingcodymiller requested changes
Hey dude!! I know you know there's still things to fix, I'm just putting in a review so you know it still needs to be addressed.

2021-03-13 00:37 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/111012519-1a31e800-8351-11eb-9c42-3614f35f6efa.png)


I was able to move the things to the left, but I think there was an easier way.

2021-03-15 17:38 UTC, codingcodymiller requested changes
Great job so far, man! You have a lot of margin going on here, though. One way you can get around this is to set a width on the `form` element, and center the content either using `margin: auto` or flexbox. Once you confine the `form` content to a certain area, the movements you will need to make will be much smaller.

2021-03-15 17:38 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-right: 25px;
That's a lot of margin!

2021-03-15 17:38 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-right: 280px;
That's a lot of margin!

2021-03-15 17:38 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-right: 400px;
That's a lot of margin!

2021-03-15 17:38 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-right: 330px;
That's a lot of margin!

2021-03-15 17:38 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  margin-left: 350px;
That's a lot of margin!

2021-03-16 08:26 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/111278059-5c2f8800-85f6-11eb-9bd9-4236961e9dad.png)

Adding the flexbox to my form container helped centering the whole thing. So whether I made the window bigger or smaller on my browser, the form remained consistent in the middle.

I couldn't figure out how to force the labels to the left side. I've tried float: left;, align-text: left.. Neither of these worked.

2021-03-18 20:03 UTC, codingcodymiller requested changes
Yo dude!! I know you still have this in progress, just wanted to give you a review so it's clear there are still changes needed. If you have any questions on how to tackle this, make sure you reach out in Slack!

2021-03-23 01:03 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/112077072-e5841480-8b38-11eb-82f4-0dcc819817dd.png)

2021-03-23 18:11 UTC, codingcodymiller approved these changes
Nice job, dude!!

2021-03-23 18:14 UTC, merged