css-media-queries | Rocky Truong
rocky-truong/c0321-code-solutions pull request #38
Opened 2021-03-25 10:20 UTC by rocky-truong

![image](https://user-images.githubusercontent.com/58172952/112457340-e5db0600-8d18-11eb-9c2c-4a9f55241629.png)

![image](https://user-images.githubusercontent.com/58172952/112457408-f7bca900-8d18-11eb-986c-120c63136467.png)

![image](https://user-images.githubusercontent.com/58172952/112457464-086d1f00-8d19-11eb-8e52-b294b85207cf.png)

2021-03-25 18:33 UTC, codingcodymiller requested changes

2021-03-25 18:33 UTC, codingcodymiller commented on css-media-queries/at-media.html
> +      body { background-color: papayawhip; }
Please always expand CSS rules to multiple lines

2021-03-25 18:33 UTC, codingcodymiller commented on css-media-queries/breakpoints.html
> +      .card-container { flex-basis: 50%; }
Please always expand CSS rules to multiple lines

2021-03-25 18:33 UTC, codingcodymiller commented on css-media-queries/breakpoints.html
> +      .card-container { flex-basis: calc(100% / 3); }
Please always expand CSS rules to multiple lines

2021-03-25 18:33 UTC, codingcodymiller commented on css-media-queries/meta-viewport.html
> +      .box { background-color: red; }
Please always expand CSS rules to multiple lines

2021-03-26 07:26 UTC, rocky-truong commented
Made the changes requested so the CSS rules would have multiple lines.

2021-03-26 18:36 UTC, codingcodymiller approved these changes

2021-03-26 23:47 UTC, merged