string-manipulation-1 | Rocky Truong
rocky-truong/c0321-code-solutions pull request #42
Opened 2021-04-02 02:03 UTC by rocky-truong

![image](https://user-images.githubusercontent.com/58172952/113372208-fc86eb80-931c-11eb-8151-c7daed6e54d7.png)

2021-04-05 17:27 UTC, codingcodymiller requested changes
Great start here!! A couple things to adjust

2021-04-05 17:27 UTC, codingcodymiller commented on string-manipulation-1/src/get-words.js
> +  }
Have you read the documentation on `split` yet? This is a very strange way to work with it, you might want to give it a review. If you use the `split` method, you won't need a loop, since `split` runs a loop for you to do its job.

2021-04-05 17:27 UTC, codingcodymiller commented on string-manipulation-1/src/is-lower-cased.js
> +  }
Again, double-check here how `lowerCase` works, you won't need to make a loop yourself.

2021-04-05 17:27 UTC, codingcodymiller commented on string-manipulation-1/src/is-upper-cased.js
> +  }
Again, double-check here how `upperCase` works, you won't need to make a loop yourself.

2021-04-06 08:10 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/113679649-d8a50c00-9674-11eb-8119-842feaa1e805.png)

2021-04-06 16:31 UTC, codingcodymiller approved these changes

2021-04-06 17:08 UTC, merged