array-manipulation-1 | Rocky Truong
rocky-truong/c0321-code-solutions pull request #50
Opened 2021-04-06 17:31 UTC by rocky-truong

![image](https://user-images.githubusercontent.com/58172952/113753730-4d069c00-96c3-11eb-8f53-0c10a13196fe.png)

2021-04-06 17:41 UTC, codingcodymiller requested changes

2021-04-06 17:41 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +  }
This is not necessary here. If the array length is zero, the below loop would never start, so you get the same situation.

2021-04-06 17:41 UTC, codingcodymiller commented on array-manipulation-1/src/reverse.js
> +  }
This is not necessary here. If the array length is zero, the below loop would never start, so you get the same situation.

2021-04-06 17:41 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +  }
This is not necessary here. If the array length is zero, the below loop would never start, so you get the same situation.

2021-04-06 18:47 UTC, rocky-truong commented
![image](https://user-images.githubusercontent.com/58172952/113762840-dde27500-96cd-11eb-8724-24c158fcead6.png)

2021-04-07 17:18 UTC, scbowler approved these changes
Great job implementing Cody's feedback, looks good! 👍 

Left a couple FYI comments below, no changes required

2021-04-07 17:18 UTC, scbowler commented on array-manipulation-1/src/compact.js
> +    if (array[i] !== false && array[i] !== null && Number.isNaN(array[i]) !== true && array[i] !== 0 && array[i] !== undefined && array[i] !== '') {
There might be a simpler way to check for a falsy value... 🤔

2021-04-08 07:19 UTC, merged